# Generated by Django 5.1.1 on 2024-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('available', 'available'), ('sold', 'sold'), ('rent', 'rent')], max_length=50)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
