# Generated by Django 5.1.1 on 2024-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_book_price_alter_book_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank='True', choices=[('fiction', 'fiction'), ('nonfiction', 'nonfiction'), ('science', 'science'), ('mystery', 'mystery'), ('fantasy', 'fantasy'), ("children's books", "children's books")], max_length=50, null='true'),
            preserve_default='true',
        ),
    ]
