# Generated by Django 5.1.1 on 2024-09-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_login_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_form',
            new_name='Login',
        ),
    ]
