# Generated by Django 5.1.1 on 2024-09-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_login_form_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank='True', choices=[('fiction', 'fiction'), ('nonfiction', 'nonfiction'), ('science', 'science'), ('mystery', 'mystery'), ('fantasy', 'fantasy'), ('children', 'children'), ('bigraphy', 'biography')], max_length=50, null='true'),
        ),
    ]
